-- ═══════════════════════════════════════════════════════════════════════════
-- The public booking flow — the writers (capabilities A1–A4; prd.md §5.1,
-- §6.1, §9.1, §9.3).
--
-- Everything the portal writes today is written by a staff member with a
-- session, a permission and a name in the audit trail. This migration adds the
-- first writers with none of those: a customer on the open internet, holding a
-- unit or a place at the pool.
--
-- Four things arrive together because none of them is useful alone.
--
-- **A private link.** `booking.access_token` is how a customer returns to a
-- booking they made ninety seconds ago. It is not the reference: architecture
-- .md §6.1 keeps `PV-4821` out of every URL precisely because it is short,
-- sequential and printed on a transfer, and a customer who can guess the next
-- one can read a stranger's booking. The token is generated by the caller from
-- node:crypto and is the same seam architecture.md §3 calls the magic link and
-- §7 will hang the QR from.
--
-- **A day pass is a row.** prd.md §6.1 has said since it was written that a
-- day pass occupies no unit and consumes facility capacity on a date. Until
-- now nothing wrote one: `booking.stream` accepted 'day_pass', the read model
-- carried it, and the only such booking in existence was a test fixture. What
-- was missing is the date — a pass is sold for a day, and a booking row has
-- nowhere to put one when there is no occupancy.
--
-- **Capacity is checked in the transaction that sells the pass**, which is
-- architecture.md §5.2's own instruction and the day-pass half of the promise
-- G1 makes for units. A unit is protected by an exclusion constraint because
-- an overlap is a property of two rows; a headcount against a ceiling is a
-- property of *every* row on that date, which no constraint can express — so
-- it is a lock, taken before the count, held to commit.
--
-- **An anonymous write is rate-limited**, because prd.md §9.3's hold is now
-- indefinite by the client's own decision (N7) and reachable by anyone with
-- the URL. A held unit costs the business a night's revenue and nothing
-- expires it. `public_attempt` is the counter that makes automated abuse cost
-- something; the honeypot on the form and the open-holds cap below are the
-- other two thirds of the answer, and none of the three is a permission.
--
-- What is deliberately NOT here: no payment row, no deposit row, no timer.
-- A public booking is created `held` and is asked for money on the next
-- screen — see 20260913000200 for the deposit it is asked for, and for
-- submit_public_payment(), which raises the pending row when the customer
-- says they have transferred.
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. booking.access_token — the private link.
--
-- Nullable, because every booking taken at the desk has no link and needs
-- none: the guest is standing there. Unique where present, via a partial
-- index — a plain unique constraint would be satisfiable by many nulls too,
-- but the partial index says out loud that null is the ordinary case.
--
-- The shape is checked rather than assumed. 16 bytes of randomness in
-- base64url is 22 characters, and a token of any other shape reaching this
-- column means a caller minted one some other way — which is the moment to
-- fail, not the moment to store it.
-- ═══════════════════════════════════════════════════════════════════════════

alter table booking add column access_token text;

alter table booking add constraint booking_access_token_shape check (
  access_token is null or access_token ~ '^[A-Za-z0-9_-]{22}$'
);

create unique index booking_access_token_idx
  on booking (access_token)
  where access_token is not null;

comment on column booking.access_token is
  'The customer''s private link to their own booking (architecture.md §3). Null for a booking taken at the desk. Never the reference, which is printed on a transfer and sequential (§6.1). 16 random bytes, base64url, minted by lib/auth/access-token.ts.';

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. guest.email gets a ceiling, and its first writer.
--
-- The column has existed since the first migration and nothing has ever
-- written it — architecture.md §9 records that email capture arrives with the
-- booking form, and this is that form. 254 is the RFC ceiling for an address;
-- an unbounded text column here is a row nobody can render in a table.
-- ═══════════════════════════════════════════════════════════════════════════

alter table guest add constraint guest_email_length check (
  email is null or char_length(email) between 3 and 254
);

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. day_pass — what was sold, for which day.
--
-- One row per day-pass booking. The composite foreign key and the
-- property-scoped uniqueness are this schema's conventions (architecture.md
-- §5.1); `unique (property_id, booking_id)` is the one that matters, because
-- a booking that is a day pass is exactly one day pass.
--
-- **The party is a jsonb snapshot, not a child table keyed on band id.** The
-- obvious shape is a row per band with a foreign key to `day_pass_age_band`,
-- and it is wrong here for the reason day_pass_bundle_line is right there: a
-- bundle's composition is configuration that must stay valid, whereas a sold
-- pass is a historic fact that must stay *readable*. A rate change is not
-- retrospective (prd.md §8, N33), so nothing ever re-prices this row; and an
-- `on delete restrict` would mean the owner could never remove an age band
-- that had ever been sold. The snapshot keeps the label as well as the id,
-- so a pass sold to "Child 1–11" still reads that way after the band is
-- renamed — which is the opposite of the rule for a unit's ref (prd.md §7.1),
-- and deliberately: a door is a place that gets relabelled, a receipt is not.
--
-- `headcount` is stored rather than summed out of the snapshot because it is
-- what capacity counts and what E5 will report, and a figure that two readers
-- derive differently is a figure that will disagree. The check keeps it
-- positive; that it AGREES with the party is the writer's job, not a
-- constraint's — jsonb arithmetic in a check constraint would be a second
-- implementation of partyFromCounts().
--
-- No status column. Whether a pass counts against capacity is the booking's
-- status, read through the join, on exactly the rule the exclusion constraint
-- uses for units: everything except expired and cancelled.
-- ═══════════════════════════════════════════════════════════════════════════

create table day_pass (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references property (id) on delete cascade,
  booking_id uuid not null,

  -- The day the pass admits them. prd.md assumption A5: a day pass is a single
  -- all-day session, not a time slot, so one date and no hours.
  pass_date date not null,

  -- Bodies through the gate, whatever they paid. A child priced at zero still
  -- occupies a place at the pool.
  headcount integer not null check (headcount > 0),

  -- [{"bandId": uuid, "label": text, "count": integer}], in the order the
  -- bands are configured.
  party jsonb not null,

  created_at timestamptz not null default now(),

  unique (property_id, id),
  unique (property_id, booking_id),
  foreign key (property_id, booking_id) references booking (property_id, id) on delete cascade
);

create index day_pass_property_date_idx on day_pass (property_id, pass_date);

comment on table day_pass is
  'What a day-pass booking sold and for which day (prd.md §6.1, §6.2). Occupies no unit; consumes facility capacity on pass_date. The party is a snapshot of the bands as they were sold, not a pointer at configuration that can move under it.';

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. day_pass_headroom — how many places are left on a date.
--
-- **The binding capacity is the smallest one among the facilities the pass
-- admits**, and that is an assumption worth stating (open-questions.md). A
-- pass admits its holder to every included facility, so the first one to fill
-- is the one that decides; taking the largest would oversell it, and summing
-- them would price a person once per pool they are standing beside.
--
-- A null capacity is not zero. prd.md C2 records that no capacity has ever
-- been agreed for any facility, so every row is null today and this function
-- returns null — which the caller reads as "no limit", the only honest reading
-- of a number nobody has given. The day the owner types one, it binds.
--
-- Facilities that are not included in the pass are ignored entirely: their
-- capacity is a fact about a facility this product does not sell.
-- ═══════════════════════════════════════════════════════════════════════════

create function day_pass_headroom(
  p_property_id uuid,
  p_from date,
  p_to date
)
returns table (pass_date date, capacity integer, taken integer)
language sql
stable
as $function$
  select
    days.day::date as pass_date,
    (
      select min(f.day_pass_capacity)::integer
      from facility f
      where f.property_id = p_property_id
        and f.included_in_day_pass
        and f.day_pass_capacity is not null
    ) as capacity,
    coalesce((
      select sum(dp.headcount)
      from day_pass dp
      join booking b
        on b.id = dp.booking_id
       and b.property_id = dp.property_id
      where dp.property_id = p_property_id
        and dp.pass_date = days.day::date
        and b.status not in ('expired', 'cancelled')
    ), 0)::integer as taken
  from generate_series(p_from, p_to, interval '1 day') as days (day)
$function$;

comment on function day_pass_headroom(uuid, date, date) is
  'Places sold and the ceiling, per date, over an inclusive range. Capacity is the smallest among facilities included in the pass; null means no limit has been configured (prd.md C2). Taken counts every pass whose booking is not expired or cancelled — the exclusion constraint''s rule, applied to a headcount.';

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. public_attempt — what an anonymous caller has been doing.
--
-- A counter, not a fact about a booking, so it is deliberately not audited and
-- deliberately not a settings row: the audit trail is the client's record of
-- what staff did, and a settings figure invites the owner to tune a control he
-- has never been told about. The thresholds live in lib/domain/public-booking
-- .ts, where they are visible to the code that applies them.
--
-- The key is hashed by the caller, never stored raw. An IP address is personal
-- data under the PDPO (prd.md §13) and a phone number certainly is; what this
-- table needs is only to tell two callers apart, which a digest does.
--
-- Fixed windows rather than a sliding one. A sliding window needs a row per
-- attempt and a sweep behind it; a fixed window is one row per key per period
-- and its worst case — twice the limit across a boundary — is irrelevant
-- against limits set where these are.
-- ═══════════════════════════════════════════════════════════════════════════

create table public_attempt (
  property_id uuid not null references property (id) on delete cascade,
  -- What was attempted: 'booking:ip', 'booking:phone', 'submit:ip'.
  kind text not null check (btrim(kind) <> '' and char_length(kind) <= 40),
  -- sha256 hex of the caller's IP or phone. Never the value itself.
  key_hash text not null check (key_hash ~ '^[0-9a-f]{64}$'),
  window_start timestamptz not null,
  count integer not null default 0 check (count >= 0),

  primary key (property_id, kind, key_hash, window_start)
);

comment on table public_attempt is
  'Rate-limit counters for unauthenticated callers (prd.md §9.3 as built). Keys are hashed — an IP and a phone are both personal data (§13). Not audited: a counter is not a fact about a booking.';

create function note_public_attempt(
  p_property_id uuid,
  p_kind text,
  p_key_hash text,
  p_window_seconds integer,
  p_limit integer
)
returns boolean
language plpgsql
as $function$
declare
  v_window_start timestamptz;
  v_count integer;
begin
  -- The window this instant falls in, floored so every caller in the same
  -- period lands on the same row and the upsert can do the counting.
  v_window_start := to_timestamp(
    floor(extract(epoch from now()) / p_window_seconds) * p_window_seconds
  );

  insert into public_attempt (property_id, kind, key_hash, window_start, count)
  values (p_property_id, p_kind, p_key_hash, v_window_start, 1)
  on conflict (property_id, kind, key_hash, window_start)
  do update set count = public_attempt.count + 1
  returning count into v_count;

  -- Swept here rather than by a scheduled job: the rows are worthless the
  -- moment their window passes, this runs on every public write anyway, and
  -- architecture.md §10 records that the cron budget is full.
  delete from public_attempt
  where property_id = p_property_id
    and window_start < now() - interval '1 day';

  return v_count <= p_limit;
end;
$function$;

comment on function note_public_attempt(uuid, text, text, integer, integer) is
  'Records one attempt and answers whether it is within the limit. Fixed windows; hashed keys; sweeps its own expired rows.';

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. create_public_stay_booking — a customer holds a unit (capability A4).
--
-- The differences from create_walk_in_booking() are all consequences of who is
-- calling.
--
-- **The customer names a type; this function picks the unit.** prd.md N9 [A]
-- has staff assigning units, and units of one type are not interchangeable
-- (bed configuration differs, §7.1), so a public form offering a choice of
-- door would be offering a decision the business has not agreed to give away.
-- It walks available_units() in ref order and takes the first that accepts the
-- occupancy row — so the assignment is made by the same constraint that
-- guarantees G1, rather than by a read that could be stale by the time it is
-- used. Each attempt is its own subtransaction: a candidate lost to a race
-- rolls back that INSERT alone and the loop tries the next door, which is what
-- turns a lost race into a different room rather than a refusal.
--
-- **It writes no payment row.** A walk-in has paid or is paying at the desk.
-- A public booking has been *made*; the money is asked for on the next screen,
-- and until the customer says they have sent it there is nothing to verify and
-- nothing to put in the queue. That is prd.md §10.3's flow with the countdown
-- struck out (N7): the unit is held, and it is held until somebody checks.
--
-- **Its status is `held`.** The first time that state is persisted anywhere —
-- architecture.md §5.3 notes that a walk-in never passes through it. The
-- occupancy row inherits it and therefore blocks the unit, because the
-- exclusion constraint excludes only expired and cancelled (§5.2).
--
-- **Its actor is null.** audit_event.actor_id has been nullable since it was
-- created, for exactly this: "the action had no authenticated actor". The
-- booking's created_by is null for the same reason, and that null is load
-- bearing below — it is how the open-holds cap tells a customer's own bookings
-- from the ones the desk made for them.
-- ═══════════════════════════════════════════════════════════════════════════

create function create_public_stay_booking(
  p_property_id uuid,
  p_unit_type_slug text,
  p_status text,
  p_check_in date,
  p_check_out date,
  p_guest_name text,
  p_guest_phone text,
  p_guest_email text,
  p_vehicles text[],
  p_no_vehicle boolean,
  p_chargeable_guests integer,
  p_exempt_guests integer,
  p_total_cents integer,
  p_security_deposit_cents integer,
  p_lines jsonb,
  p_access_token text,
  p_max_open_per_phone integer
)
returns jsonb
language plpgsql
as $function$
declare
  v_guest_id uuid;
  v_booking_id uuid;
  v_reference text;
  v_vehicles text[] := coalesce(p_vehicles, '{}'::text[]);
  v_email text := nullif(btrim(coalesce(p_guest_email, '')), '');
  v_open integer;
  v_candidate record;
  v_unit_id uuid;
  v_unit_ref text;
begin
  if cardinality(v_vehicles) = 0 and not p_no_vehicle then
    raise exception 'a booking needs at least one vehicle registration, or the no-vehicle exception';
  end if;

  -- How many units this phone number is already holding without having paid
  -- for any of them. The cap is the part of the abuse answer that a honeypot
  -- and a request counter cannot give: a patient human with a real browser can
  -- defeat both, and the thing worth protecting is inventory rather than
  -- bandwidth. `created_by is null` narrows it to bookings the customer made
  -- themselves — a desk that takes four advance bookings for one regular is
  -- doing its job and must not trip this.
  select count(*)
  into v_open
  from booking b
  join guest g on g.id = b.guest_id
  where b.property_id = p_property_id
    and b.created_by is null
    and b.status in ('held', 'awaiting_payment_verification')
    and g.phone = p_guest_phone;

  if v_open >= p_max_open_per_phone then
    return jsonb_build_object('ok', false, 'error', 'too_many_open_bookings');
  end if;

  -- No de-duplication, the position create_walk_in_booking() takes and for the
  -- same reason: merging two people who share a phone is worse than a
  -- duplicate row, and amend_booking() edits the guest in place on the
  -- assumption that each booking owns one.
  insert into guest (property_id, name, phone, email)
  values (p_property_id, p_guest_name, p_guest_phone, v_email)
  returning id into v_guest_id;

  v_reference := next_booking_reference();

  insert into booking (
    property_id, reference, stream, status, guest_id,
    chargeable_guests, exempt_guests, no_vehicle,
    total_cents, security_deposit_cents, access_token, created_by
  )
  values (
    p_property_id, v_reference, 'short_stay', p_status, v_guest_id,
    p_chargeable_guests, p_exempt_guests, p_no_vehicle,
    p_total_cents, p_security_deposit_cents, p_access_token, null
  )
  returning id into v_booking_id;

  insert into booking_vehicle (property_id, booking_id, registration, sort_order)
  select p_property_id, v_booking_id, plate, (ordinality - 1)::integer
  from unnest(v_vehicles) with ordinality as plates (plate, ordinality);

  insert into booking_line (
    property_id, booking_id, line_type, description,
    quantity, unit_price_cents, amount_cents, sort_order
  )
  select
    p_property_id,
    v_booking_id,
    entry ->> 'type',
    entry ->> 'description',
    (entry ->> 'quantity')::integer,
    (entry ->> 'unitPrice')::integer,
    (entry ->> 'amount')::integer,
    (ordinality - 1)::integer
  from jsonb_array_elements(p_lines) with ordinality as elements (entry, ordinality);

  -- ── The assignment ───────────────────────────────────────────────────────
  --
  -- Serialised per unit type, and the lock is not optional. Without it eight
  -- customers asking for the same type walk the same candidate list in the
  -- same order, and the exclusion constraint makes an inserting transaction
  -- WAIT on a conflicting uncommitted one rather than fail — so two of them
  -- end up holding a door each and waiting on the other's, which Postgres
  -- resolves by killing somebody's booking with "deadlock detected". That is
  -- a customer seeing an error on a building with forty free rooms, and it is
  -- what lib/db/public-bookings.test.ts caught.
  --
  -- Per type rather than per property, so a family booking a semi-detached
  -- never queues behind somebody booking an apartment. Transaction-scoped, so
  -- it is released by the commit or rollback that settles the booking.
  --
  -- **This does not replace the constraint**, it only removes the cycle among
  -- public callers. The desk takes no such lock, so a walk-in and a customer
  -- can still race for the same door — and the exclusion constraint is what
  -- decides that, exactly as capability G1 promises. The handlers below are
  -- what turn its refusal into the next room rather than an apology.
  perform pg_advisory_xact_lock(hashtext(p_property_id::text || ':assign:' || p_unit_type_slug));

  -- available_units() applies the identical half-open overlap and
  -- out-of-service rules the constraint and the trigger apply, so an ordinary
  -- call finds a free door on its first attempt.
  for v_candidate in
    select id, ref
    from available_units(p_property_id, p_check_in, p_check_out, p_unit_type_slug, null)
  loop
    begin
      insert into occupancy (
        property_id, unit_id, booking_id, occupancy_type, status, start_date, end_date
      )
      values (
        p_property_id, v_candidate.id, v_booking_id, 'short_stay', p_status,
        p_check_in, p_check_out
      );

      v_unit_id := v_candidate.id;
      v_unit_ref := v_candidate.ref;
      exit;
    exception
      -- Somebody took this door between the read and this statement. Not a
      -- failure of the booking — only of this candidate.
      when exclusion_violation then
        null;
      -- And the unit went out of service in the same window. Same answer:
      -- try the next one. Named rather than swallowed with `others`, which
      -- would hide a genuine fault as a full building.
      when sqlstate 'PV002' then
        null;
    end;
  end loop;

  if v_unit_id is null then
    -- Raised rather than returned, so the guest and the booking written above
    -- are rolled back by this function's own exception handler. A guest row
    -- left behind by a booking that never existed is a data-protection
    -- liability with no purpose (prd.md §13) — the position
    -- no-double-booking.test.ts already asserts for the walk-in path.
    raise exception 'no unit of this type is free' using errcode = 'PV004';
  end if;

  insert into audit_event (
    property_id, actor_id, action, entity_type, entity_id, before, after
  )
  values (
    p_property_id,
    null,
    'booking.created_public',
    'booking',
    v_booking_id,
    null,
    jsonb_build_object(
      'reference', v_reference,
      'status', p_status,
      'stream', 'short_stay',
      'unit_id', v_unit_id,
      'unit_ref', v_unit_ref,
      'check_in', p_check_in,
      'check_out', p_check_out,
      'total_cents', p_total_cents,
      'security_deposit_cents', p_security_deposit_cents,
      'vehicles', to_jsonb(v_vehicles),
      'no_vehicle', p_no_vehicle
    )
  );

  return jsonb_build_object(
    'ok', true,
    'booking_id', v_booking_id,
    'reference', v_reference,
    'unit_id', v_unit_id,
    'unit_ref', v_unit_ref,
    'access_token', p_access_token
  );

exception
  when sqlstate 'PV004' then
    return jsonb_build_object('ok', false, 'error', 'unit_unavailable');
  when unique_violation then
    -- The access token collided, which at 128 bits of randomness means the
    -- caller reused one. Returned rather than raised so the action can mint
    -- another and try again instead of showing a customer a stack trace.
    return jsonb_build_object('ok', false, 'error', 'token_collision');
end;
$function$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. create_public_day_pass_booking — the first day pass anything sells (A3).
--
-- The capacity check is the whole of the interesting part, and it is
-- architecture.md §5.2's instruction taken literally: "a transactional check
-- against the configured facility headroom for the date, with the booking
-- insert and the count in one transaction".
--
-- **The lock is per date, and it is taken before the count.** Two customers
-- buying the last two places on the same day must not both read "one left";
-- an advisory lock keyed on the property and the date serialises exactly those
-- two and nobody else, so a busy Saturday does not queue behind a quiet
-- Tuesday. It is a transaction-scoped lock, so it is released by the commit
-- or rollback that settles the question — there is nothing to unlock by hand
-- and no path that can leak one.
--
-- An advisory lock rather than a row lock because there is no row to lock: a
-- date with no passes sold has nothing in day_pass, and inventing a row per
-- date to lock would be a calendar table maintained for the sake of a lock.
-- ═══════════════════════════════════════════════════════════════════════════

create function create_public_day_pass_booking(
  p_property_id uuid,
  p_status text,
  p_pass_date date,
  p_party jsonb,
  p_headcount integer,
  p_chargeable_guests integer,
  p_exempt_guests integer,
  p_guest_name text,
  p_guest_phone text,
  p_guest_email text,
  p_vehicles text[],
  p_no_vehicle boolean,
  p_total_cents integer,
  p_lines jsonb,
  p_access_token text,
  p_max_open_per_phone integer
)
returns jsonb
language plpgsql
as $function$
declare
  v_guest_id uuid;
  v_booking_id uuid;
  v_reference text;
  v_vehicles text[] := coalesce(p_vehicles, '{}'::text[]);
  v_email text := nullif(btrim(coalesce(p_guest_email, '')), '');
  v_open integer;
  v_capacity integer;
  v_taken integer;
begin
  select count(*)
  into v_open
  from booking b
  join guest g on g.id = b.guest_id
  where b.property_id = p_property_id
    and b.created_by is null
    and b.status in ('held', 'awaiting_payment_verification')
    and g.phone = p_guest_phone;

  if v_open >= p_max_open_per_phone then
    return jsonb_build_object('ok', false, 'error', 'too_many_open_bookings');
  end if;

  -- Serialise everyone buying a pass for this date. hashtext over the pair
  -- collides across dates at a rate that costs a wait and never a wrong
  -- answer, which is the right trade for a lock key.
  perform pg_advisory_xact_lock(hashtext(p_property_id::text || ':' || p_pass_date::text));

  select h.capacity, h.taken
  into v_capacity, v_taken
  from day_pass_headroom(p_property_id, p_pass_date, p_pass_date) h;

  -- Null capacity is no limit (prd.md C2 — no number has ever been agreed).
  if v_capacity is not null and v_taken + p_headcount > v_capacity then
    return jsonb_build_object(
      'ok', false,
      'error', 'capacity_exceeded',
      'remaining', greatest(v_capacity - v_taken, 0)
    );
  end if;

  insert into guest (property_id, name, phone, email)
  values (p_property_id, p_guest_name, p_guest_phone, v_email)
  returning id into v_guest_id;

  v_reference := next_booking_reference();

  -- No occupancy row, and no security deposit. A day pass occupies no unit
  -- (prd.md §6.1) and nothing in the PRD holds a deposit against one: the
  -- BND 100 secures a stay in a room, and there is no room here.
  insert into booking (
    property_id, reference, stream, status, guest_id,
    chargeable_guests, exempt_guests, no_vehicle,
    total_cents, security_deposit_cents, access_token, created_by
  )
  values (
    p_property_id, v_reference, 'day_pass', p_status, v_guest_id,
    p_chargeable_guests, p_exempt_guests, p_no_vehicle,
    p_total_cents, 0, p_access_token, null
  )
  returning id into v_booking_id;

  insert into booking_vehicle (property_id, booking_id, registration, sort_order)
  select p_property_id, v_booking_id, plate, (ordinality - 1)::integer
  from unnest(v_vehicles) with ordinality as plates (plate, ordinality);

  insert into booking_line (
    property_id, booking_id, line_type, description,
    quantity, unit_price_cents, amount_cents, sort_order
  )
  select
    p_property_id,
    v_booking_id,
    entry ->> 'type',
    entry ->> 'description',
    (entry ->> 'quantity')::integer,
    (entry ->> 'unitPrice')::integer,
    (entry ->> 'amount')::integer,
    (ordinality - 1)::integer
  from jsonb_array_elements(p_lines) with ordinality as elements (entry, ordinality);

  insert into day_pass (property_id, booking_id, pass_date, headcount, party)
  values (p_property_id, v_booking_id, p_pass_date, p_headcount, p_party);

  insert into audit_event (
    property_id, actor_id, action, entity_type, entity_id, before, after
  )
  values (
    p_property_id,
    null,
    'booking.created_public',
    'booking',
    v_booking_id,
    null,
    jsonb_build_object(
      'reference', v_reference,
      'status', p_status,
      'stream', 'day_pass',
      'pass_date', p_pass_date,
      'headcount', p_headcount,
      'total_cents', p_total_cents,
      'vehicles', to_jsonb(v_vehicles),
      'no_vehicle', p_no_vehicle
    )
  );

  return jsonb_build_object(
    'ok', true,
    'booking_id', v_booking_id,
    'reference', v_reference,
    'access_token', p_access_token
  );

exception
  when unique_violation then
    return jsonb_build_object('ok', false, 'error', 'token_collision');
end;
$function$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. The read model carries what the public flow writes.
--
-- Appended, because `create or replace view` allows a new column only at the
-- end (the lesson paid_cents and deposit_waiver_reason already recorded).
--
-- booking_summary gains the guest's email, the pass date and the headcount.
-- The pass date is what makes prd.md §6.1's promise legible on a screen: the
-- bookings register has been drawing an em dash in its Dates cell for every
-- day pass, correctly, because there was no date to draw. Now there is.
--
-- payment_summary gains the pass date for the same reason — the verification
-- queue's Arriving column reads occupancy, and a day pass has none.
-- ═══════════════════════════════════════════════════════════════════════════

create or replace view booking_summary
with (security_invoker = true)
as
select
  b.id,
  b.property_id,
  b.reference,
  b.status,
  b.stream,
  g.name as guest_name,
  g.phone as guest_phone,
  b.chargeable_guests,
  b.exempt_guests,
  b.total_cents,
  b.security_deposit_cents,
  b.hold_expires_at,
  b.created_at,
  b.updated_at,
  b.no_vehicle,
  o.unit_id,
  u.ref as unit_ref,
  ut.slug as unit_type_slug,
  o.start_date as check_in,
  o.end_date as check_out,
  coalesce(l.lines, '[]'::jsonb) as lines,
  coalesce(v.vehicles, '[]'::jsonb) as vehicles,
  b.discount_kind,
  b.discount_value,
  b.discount_reason,
  coalesce(pay.paid_cents, 0)::integer as paid_cents,
  b.deposit_waiver_reason,
  g.email as guest_email,
  dp.pass_date,
  dp.headcount as pass_headcount,
  b.access_token
from booking b
join guest g on g.id = b.guest_id
left join occupancy o on o.booking_id = b.id
left join unit u on u.id = o.unit_id
left join unit_type ut on ut.id = u.unit_type_id
left join day_pass dp on dp.booking_id = b.id
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'type', bl.line_type,
      'description', bl.description,
      'quantity', bl.quantity,
      'unitPrice', bl.unit_price_cents,
      'amount', bl.amount_cents
    )
    order by bl.sort_order
  ) as lines
  from booking_line bl
  where bl.booking_id = b.id
) l on true
left join lateral (
  select jsonb_agg(bv.registration order by bv.sort_order) as vehicles
  from booking_vehicle bv
  where bv.booking_id = b.id
) v on true
left join lateral (
  select sum(p.amount_cents) as paid_cents
  from payment p
  where p.booking_id = b.id and p.status = 'verified'
) pay on true;

create or replace view payment_summary
with (security_invoker = true)
as
select
  p.id,
  p.property_id,
  p.booking_id,
  p.method,
  p.status,
  p.expected_amount_cents,
  p.amount_cents,
  p.observed_reference,
  p.observed_sender,
  p.observed_on,
  p.match_kind,
  p.amount_override_reason,
  p.match_reason,
  p.collected_by,
  p.collected_at,
  p.verified_by,
  p.verified_at,
  p.created_by,
  p.created_at,
  p.slip_document_id,
  b.reference as booking_reference,
  b.status as booking_status,
  (b.total_cents - coalesce(other.paid_cents, 0))::integer as due_amount_cents,
  b.updated_at as booking_updated_at,
  g.name as guest_name,
  g.phone as guest_phone,
  o.start_date as check_in,
  u.ref as unit_ref,
  b.stream as booking_stream,
  dp.pass_date
from payment p
join booking b on b.id = p.booking_id
join guest g on g.id = b.guest_id
left join occupancy o on o.booking_id = b.id
left join unit u on u.id = o.unit_id
left join day_pass dp on dp.booking_id = b.id
left join lateral (
  select sum(other_payment.amount_cents) as paid_cents
  from payment other_payment
  where other_payment.booking_id = b.id
    and other_payment.status = 'verified'
    and other_payment.id <> p.id
) other on true;

-- ═══════════════════════════════════════════════════════════════════════════
-- 9. Grants.
--
-- Service role only, like every other writer here. The public flow is
-- unauthenticated at the browser and privileged at the server: architecture.md
-- §2 keeps every query behind lib/supabase/data.ts, so "anonymous" describes
-- the customer and never the database connection. RLS stays enabled with no
-- policies, which is what makes the anon key see nothing at all.
-- ═══════════════════════════════════════════════════════════════════════════

revoke all on day_pass from public, anon, authenticated;
grant select, insert on day_pass to service_role;

revoke all on public_attempt from public, anon, authenticated;
grant select, insert, update, delete on public_attempt to service_role;

revoke execute on function day_pass_headroom(uuid, date, date)
  from public, anon, authenticated;
revoke execute on function note_public_attempt(uuid, text, text, integer, integer)
  from public, anon, authenticated;
revoke execute on function create_public_stay_booking(
  uuid, text, text, date, date, text, text, text, text[], boolean,
  integer, integer, integer, integer, jsonb, text, integer
) from public, anon, authenticated;
revoke execute on function create_public_day_pass_booking(
  uuid, text, date, jsonb, integer, integer, integer, text, text, text,
  text[], boolean, integer, jsonb, text, integer
) from public, anon, authenticated;

grant execute on function day_pass_headroom(uuid, date, date) to service_role;
grant execute on function note_public_attempt(uuid, text, text, integer, integer) to service_role;
grant execute on function create_public_stay_booking(
  uuid, text, text, date, date, text, text, text, text[], boolean,
  integer, integer, integer, integer, jsonb, text, integer
) to service_role;
grant execute on function create_public_day_pass_booking(
  uuid, text, date, jsonb, integer, integer, integer, text, text, text,
  text[], boolean, integer, jsonb, text, integer
) to service_role;
